### ISSUE TITLE
Inference problems for all Qwen2.5 VL models in transformers above 4.49.0

### ISSUE THREAD

**Issue by mirekphd** [QwenLM/Qwen2.5-VL#1033]
I've been having various inference problems (such as value errors or garbled output) with AWQ quantizations of Qwen2.5 VL models of various sizes (from 3B to 72B) **since `transformers` package got upgraded to v4.50.0.**

These problems persist in **all versions of `transformers` above 4.49.0** (including latest ones: 4.50.2 and 4.50.3). 

They occur **regardless of whether Flash Attention is used** or not and for all models sizes (I tested: 3B, 7B, and 72B). 

A quick workaround is to downgrade `transformers` (at the cost of supporting new competing VLM models such as Gemma 3 series) to its last version supported by Qwen2.5 VL, e.g. thus:

```
pip install transformers"<4.50.0"
```
_____________________

They should be easy to reproduce, as long as you use VL models (of any size) and AWQ quant. (standard Qwen2.5 LLMs in AWQ quant. are OK, i.e. compatible with the latest `transformers` versions).

Example error message (for the 7B model on an RTX 3090 GPU w/ Flash Attention):
```
Some weights of the model checkpoint at Qwen/Qwen2.5-VL-7B-Instruct-AWQ were not used when initializing Qwen2_5_VLForConditionalGeneration: ['lm_head.weight']
- This IS expected if you are initializing Qwen2_5_VLForConditionalGeneration from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Qwen2_5_VLForConditionalGeneration from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Qwen2_5_VLForConditionalGeneration were not initialized from the model checkpoint at Qwen/Qwen2.5-VL-7B-Instruct-AWQ and are newly initialized: ['lm_head.qweight', 'lm_head.qzeros', 'lm_head.scales']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.50, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
/pytorch/aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `probability tensor contains either `inf`, `nan` or element < 0` failed.
Traceback (most recent call last):
  File "/home/jovyan/work/test-qwen2.5-vl-7b.py", line 56, in <module>
    generated_ids = model.generate(**inputs, max_new_tokens=128)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/generation/utils.py", line 2326, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/generation/utils.py", line 3332, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Example garbled output (for the 72B model on a A100 GPU w/o Flash Attention) is a short string of UTF-8 characters resembling Korean language (but not translatable to English).

**Comment by chengyuehuang511** [comment]
I have the similar issue - when I use Qwen/Qwen2.5-VL-72B-Instruct-AWQ under transformers-4.51.0.dev0 with torch.float16, there's error "RuntimeError: probability tensor contains either `inf`, `nan` or element < 0", while with torch.bfloat16 there's "AssertionError: Both operands must be same dtype. Got fp16 and bf16". After downgrading to transformers-4.49.0 everything works.

**Comment by ttppss** [comment]
> I've been having various inference problems (such as value errors or garbled output) with AWQ quantizations of Qwen2.5 VL models of various sizes (from 3B to 72B) **since `transformers` package got upgraded to v4.50.0.**
> 
> These problems persist in **all versions of `transformers` above 4.49.0** (including latest ones: 4.50.2 and 4.50.3).
> 
> They occur **regardless of whether Flash Attention is used** or not and for all models sizes (I tested: 3B, 7B, and 72B).
> 
> A quick workaround is to downgrade `transformers` (at the cost of supporting new competing VLM models such as Gemma 3 series) to its last version supported by Qwen2.5 VL, e.g. thus:
> 
> ```
> pip install transformers"<4.50.0"
> ```
> 
> They should be easy to reproduce, as long as you use VL models (of any size) and AWQ quant. (standard Qwen2.5 LLMs in AWQ quant. are OK, i.e. compatible with the latest `transformers` versions).
> 
> Example error message (for the 7B model on an RTX 3090 GPU w/ Flash Attention):
> 
> ```
> Some weights of the model checkpoint at Qwen/Qwen2.5-VL-7B-Instruct-AWQ were not used when initializing Qwen2_5_VLForConditionalGeneration: ['lm_head.weight']
> - This IS expected if you are initializing Qwen2_5_VLForConditionalGeneration from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing Qwen2_5_VLForConditionalGeneration from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> Some weights of Qwen2_5_VLForConditionalGeneration were not initialized from the model checkpoint at Qwen/Qwen2.5-VL-7B-Instruct-AWQ and are newly initialized: ['lm_head.qweight', 'lm_head.qzeros', 'lm_head.scales']
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.50, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
> /pytorch/aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `probability tensor contains either `inf`, `nan` or element < 0` failed.
> Traceback (most recent call last):
>   File "/home/jovyan/work/test-qwen2.5-vl-7b.py", line 56, in <module>
>     generated_ids = model.generate(**inputs, max_new_tokens=128)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/conda/lib/python3.11/site-packages/transformers/generation/utils.py", line 2326, in generate
>     result = self._sample(
>              ^^^^^^^^^^^^^
>   File "/opt/conda/lib/python3.11/site-packages/transformers/generation/utils.py", line 3332, in _sample
>     next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: CUDA error: device-side assert triggered
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> ```
> 
> Example garbled output (for the 72B model on a A100 GPU w/o Flash Attention) is a short string of UTF-8 characters resembling Korean language (but not translatable to English).

I met the same issue, and @chengyuehuang511 I'm sorry it didn't work out for me.

**Comment by ttppss** [comment]
Having the same issue, and downgrading 'transformers' cannot solve my issue. 

`Loading checkpoint shards: 100%|███████████████████████████████████████████████| 5/5 [00:04<00:00,  1.09it/s]
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
text: <|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
Read all the text in the image.<|vision_start|><|image_pad|><|vision_end|><|im_end|>
<|im_start|>assistant

/pytorch/aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `probability tensor contains either `inf`, `nan` or element < 0` failed.
Traceback (most recent call last):
  File "/home/usr/projects/Qwen2.5-VL/inference.py", line 164, in <module>
    response = inference(image_path, prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/projects/Qwen2.5-VL/inference.py", line 96, in inference
    output_ids = model.generate(**inputs, max_new_tokens=max_new_tokens)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/miniconda3/envs/qwen/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/usr/miniconda3/envs/qwen/lib/python3.11/site-packages/transformers/generation/utils.py", line 2223, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/home/usr/miniconda3/envs/qwen/lib/python3.11/site-packages/transformers/generation/utils.py", line 3257, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

**Comment by ziqipang** [comment]
Same here

**Comment by ziqipang** [comment]
Not sure if this is helpful for everyone here. I delved into this issue and found the probability for multinomial being `nan`. Then I realized that it is critical to set the correct data type. Please check if you have used `torch.bfloat16` when initializing.

```python
model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
        args.model_path,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        attn_implementation="flash_attention_2"
    )
```

**Comment by ziqipang** [comment]
Not sure if this is helpful for everyone here. I delved into this issue and found the probability for multinomial being `nan`. Then I realized that it is critical to set the correct data type. Please check if you have used `torch.bfloat16` when initializing.

```python
model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
        args.model_path,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        attn_implementation="flash_attention_2"
    )
```

**Comment by yidamyth** [comment]
can't fixed it, also have the problem


Traceback (most recent call last):
  File "/home/yida/PyCharmProject/My_Paper/CoT-RLFuse/Model/Architecture/clip_model.py", line 684, in <module>
    y,_, extracted_batch_output = net(vis, ir)
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yida/PyCharmProject/My_Paper/CoT-RLFuse/Model/Architecture/clip_model.py", line 635, in forward
    extracted_output = batch_generate_and_extract_features(
  File "/home/yida/PyCharmProject/My_Paper/CoT-RLFuse/Model/Architecture/clip_model.py", line 177, in batch_generate_and_extract_features
    outputs = model.generate(
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/transformers/generation/utils.py", line 2223, in generate
    result = self._sample(
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/transformers/generation/utils.py", line 3257, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by yidamyth** [comment]
> Having the same issue, and downgrading 'transformers' cannot solve my issue.遇到同样的问题，降级'transformers'无法解决我的问题。
> 
> `Loading checkpoint shards: 100%|███████████████████████████████████████████████| 5/5 [00:04<00:00, 1.09it/s] Using a slow image processor as `use_fast`is unset and a slow processor was saved with this model.`use_fast=True`will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with`use_fast=False`. text: <|im_start|>system<|im_start|>system You are a helpful assistant.<|im_end|>你是一个有帮助的助手。<|im_end|> <|im_start|>user Read all the text in the image.<|vision_start|><|image_pad|><|vision_end|><|im_end|>阅读图片中的所有文字。<|vision_start|><|image_pad|><|vision_end|><|im_end|> <|im_start|>assistant
> 
> /pytorch/aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `probability tensor contains either `inf`, `nan` or element < 0` failed./pytorch/aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] 断言 `probability tensor contains either ` 无穷大 `, ` NaN ` or element < 0` 失败。 Traceback (most recent call last): Traceback (最近调用最后): File "/home/usr/projects/Qwen2.5-VL/inference.py", line 164, in 文件 "/home/usr/projects/Qwen2.5-VL/inference.py", 行 164, 在 response = inference(image_path, prompt) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/usr/projects/Qwen2.5-VL/inference.py", line 96, in inference output_ids = model.generate(**inputs, max_new_tokens=max_new_tokens) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/usr/miniconda3/envs/qwen/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/home/usr/miniconda3/envs/qwen/lib/python3.11/site-packages/transformers/generation/utils.py", line 2223, in generate 文件 "/home/usr/miniconda3/envs/qwen/lib/python3.11/site-packages/transformers/generation/utils.py"，第 2223 行，在 generate 函数中 result = self._sample( ^^^^^^^^^^^^^ File "/home/usr/miniconda3/envs/qwen/lib/python3.11/site-packages/transformers/generation/utils.py", line 3257, in _sample 文件 "/home/usr/miniconda3/envs/qwen/lib/python3.11/site-packages/transformers/generation/utils.py"，第 3257 行，在 _sample 函数中 next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ RuntimeError: CUDA error: device-side assert triggered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

请问您是如何解决问题的，我也遇见相同问题，且降级transformer是仍然无法解决该问题。

**Comment by yidamyth** [comment]
> torch_dtype=torch.bfloat16,
>         device_map="auto",
>         attn_implementation="flash_attention_2"

The problem can't be solved and it still reports an error。


Traceback (most recent call last):
  File "/home/yida/PyCharmProject/My_Paper/CoT-RLFuse/Model/Architecture/clip_model.py", line 685, in <module>
    y,_, extracted_batch_output = net(vis, ir)
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yida/PyCharmProject/My_Paper/CoT-RLFuse/Model/Architecture/clip_model.py", line 636, in forward
    extracted_output = batch_generate_and_extract_features(
  File "/home/yida/PyCharmProject/My_Paper/CoT-RLFuse/Model/Architecture/clip_model.py", line 178, in batch_generate_and_extract_features
    outputs = model.generate(
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/transformers/generation/utils.py", line 2223, in generate
    result = self._sample(
  File "/home/yida/miniconda3/envs/Cot-RLFuse/lib/python3.10/site-packages/transformers/generation/utils.py", line 3257, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by ttppss** [comment]
> > Having the same issue, and downgrading 'transformers' cannot solve my issue.遇到同样的问题，降级'transformers'无法解决我的问题。
> > `Loading checkpoint shards: 100%|███████████████████████████████████████████████| 5/5 [00:04<00:00, 1.09it/s] Using a slow image processor as `use_fast`is unset and a slow processor was saved with this model.`use_fast=True`will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with`use_fast=False`. text: <|im_start|>system<|im_start|>system You are a helpful assistant.<|im_end|>你是一个有帮助的助手。<|im_end|> <|im_start|>user Read all the text in the image.<|vision_start|><|image_pad|><|vision_end|><|im_end|>阅读图片中的所有文字。<|vision_start|><|image_pad|><|vision_end|><|im_end|> <|im_start|>assistant
> > /pytorch/aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] Assertion `probability tensor contains either `inf`, `nan` or element < 0` failed./pytorch/aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,0] 断言 `probability tensor contains either ` 无穷大 `, ` NaN ` or element < 0` 失败。 Traceback (most recent call last): Traceback (最近调用最后): File "/home/usr/projects/Qwen2.5-VL/inference.py", line 164, in 文件 "/home/usr/projects/Qwen2.5-VL/inference.py", 行 164, 在 response = inference(image_path, prompt) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/usr/projects/Qwen2.5-VL/inference.py", line 96, in inference output_ids = model.generate(**inputs, max_new_tokens=max_new_tokens) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/usr/miniconda3/envs/qwen/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/home/usr/miniconda3/envs/qwen/lib/python3.11/site-packages/transformers/generation/utils.py", line 2223, in generate 文件 "/home/usr/miniconda3/envs/qwen/lib/python3.11/site-packages/transformers/generation/utils.py"，第 2223 行，在 generate 函数中 result = self._sample( ^^^^^^^^^^^^^ File "/home/usr/miniconda3/envs/qwen/lib/python3.11/site-packages/transformers/generation/utils.py", line 3257, in _sample 文件 "/home/usr/miniconda3/envs/qwen/lib/python3.11/site-packages/transformers/generation/utils.py"，第 3257 行，在 _sample 函数中 next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ RuntimeError: CUDA error: device-side assert triggered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`
> 
> 请问您是如何解决问题的，我也遇见相同问题，且降级transformer是仍然无法解决该问题。

不太记得了，当下也没解决，后来过了几周不记得做了些什么操作就好了

**Comment by yidamyth** [comment]
已解决

**Comment by yidamyth** [comment]
> 已解决

https://yidamyth.blog.csdn.net/article/details/148848597?fromshare=blogdetail&sharetype=blogdetail&sharerId=148848597&sharerefer=PC&sharesource=weixin_43312117&sharefrom=from_link

**Comment by Erin110** [comment]
### Qwen2.5-VL系列在A100多卡环境下出现概率张量异常的解决方案

#### 问题描述
在4090显卡上能够正常运行的Qwen2.5-VL模型部署代码，在A100系列显卡上运行时出现以下错误：
```python
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```
经过排查，确认模型权重未损坏，尝试官方推荐的transformers库降级、重装等方案均无效。

#### 临时解决方案
通过指定仅使用单张显卡可以暂时解决此问题，在代码中添加以下环境变量设置：
```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "3"  # 指定使用第四张显卡(索引从0开始)
```
此方法能够保证模型在单卡环境下正常运行，但无法支持多卡并行计算。

#### 问题分析与可能的根本原因
1. **显卡硬件差异**：A100与4090在显存结构、内存带宽和计算能力上存在显著差异，可能导致在处理大型模型时出现数值稳定性问题
2. **多卡通信问题**：多卡环境下的NCCL库配置或通信机制可能存在兼容性问题
3. **精度与舍入误差**：不同显卡对FP16/FP32混合精度的处理方式可能引发数值溢出或下溢
4. **环境配置差异**：A100服务器上的CUDA版本、驱动程序或其他依赖库可能与4090环境不完全一致

**Comment by wcbup** [comment]
I tried all the methods mentioned above, but none of them worked.

In the end, I solved this problem by changing all png inputs to jpg. It may sound wild, but it really solves my problem.
