### ISSUE TITLE
Finetuning Qwen 2.5 VL 3B with Deepspeed is hanging and not progressing on a g5.12xlarge (4 A10 Gpus)

### ISSUE THREAD

**Issue by anindya-saha** [QwenLM/Qwen2.5-VL#1173]
Hello Team, 

I am following the instructions from https://github.com/QwenLM/Qwen2.5-VL/tree/main/qwen-vl-finetune to finetune Qwen 2.5 VL with DeepSpeed on the TIGER-Lab/VisualWebInstruct. 

I am using a AWS g5.12xlarge instance which has 4 A10 GPUs with 24 GB VRAM each. 

The training does not proceed at all and just hangs

The data init script is a simple modification of the original and is as follows:

```
VISUALWEBINSTRUCT = {
    "annotation_path": /home/asaha/VisualWebInstruct/mixed_conversation.jsonl",
    "data_path": "/home/asaha/VisualWebInstruct/images",
}

data_dict = {
    "visualwebinstruct": VISUALWEBINSTRUCT,
}
```

The training init script is a simple modification of the original and is as follows:

```
#!/bin/bash

# Enable error handling
set -e

# Distributed training configuration
MASTER_ADDR=${MASTER_ADDR:-"127.0.0.1"}
MASTER_PORT=${MASTER_PORT:-$(shuf -i 20001-29999 -n 1)}
NNODES=${WORLD_SIZE:-1}
NPROC_PER_NODE=4

HF_HOME="<some folder>hf_cache"

# Add debugging flags
TORCH_DISTRIBUTED_DEBUG=INFO
NCCL_DEBUG=INFO
PYTHONUNBUFFERED=1

# DeepSpeed configuration
deepspeed=./scripts/zero3.json

# Model configuration
llm=Qwen/Qwen2.5-VL-3B-Instruct  # Using HuggingFace model ID

# Training hyperparameters
lr=2e-7
batch_size=4  # Reduced batch size
grad_accum_steps=4  # Increased gradient accumulation

# Training entry point
entry_file=qwenvl/train/train_qwen.py

# Dataset configuration (replace with public dataset names)
datasets="visualwebinstruct%100"

# Output configuration
run_name="qwen2vl-baseline"
output_dir=./output

# Training arguments
args="
    --deepspeed ${deepspeed} \
    --model_name_or_path "${llm}" \
    --dataset_use ${datasets} \
    --data_flatten True \
    --tune_mm_vision False \
    --tune_mm_mlp True \
    --tune_mm_llm True \
    --output_dir ${output_dir} \
    --num_train_epochs 1 \
    --per_device_train_batch_size ${batch_size} \
    --per_device_eval_batch_size $((batch_size*2)) \
    --gradient_accumulation_steps ${grad_accum_steps} \
    --max_pixels 50176 \
    --min_pixels 784 \
    --eval_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate ${lr} \
    --weight_decay 0 \
    --warmup_ratio 0.03 \
    --max_grad_norm 1 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --model_max_length 8192 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --run_name ${run_name} \
    --bf16 True \
    --report_to none"

# Create log directory if it doesn't exist
if [ ! -d "logs" ]; then
    mkdir -p logs
fi

# Launch training with proper logging
torchrun \
    --nproc_per_node=${NPROC_PER_NODE} \
    --master_addr=${MASTER_ADDR} \
    --master_port=${MASTER_PORT} \
    --log_dir=logs \
    ${entry_file} ${args} 2>&1 | tee logs/training_$(date +%Y%m%d_%H%M%S).log
```

**Comment by John-Ge** [comment]
Hello, I download the data and here is one of the item:
```json
{"conversations": [{"from": "human", "value": "Which of the following shows the graph of the line with a slope of $2$ and goes through the point $(1, 2)$?\n\nPlease conclude your answer as Answer: xxx at the end if possible."}, {"from": "gpt", "value": "To find the graph of a line with a given slope and point, we can use the point-slope form of the equation of a line:\n\n\\[ y - y_1 = m(x - x_1) \\]\n\nWhere \\( m \\) is the slope and \\( (x_1, y_1) \\) is the given point on the line.\n\nGiven:\n- Slope (\\( m \\)) = 2\n- Point (\\( x_1, y_1 \\)) = (1, 2)\n\nPlug these values into the point-slope formula:\n\n\\[ y - 2 = 2(x - 1) \\]\n\nNow, simplify this equation to get it into slope-intercept form \\( y = mx + b \\):\n\n1. Distribute the slope (2) on the right side:\n   \\[ y - 2 = 2x - 2 \\]\n\n2. Add 2 to both sides to solve for \\( y \\):\n   \\[ y = 2x - 2 + 2 \\]\n\n3. Simplify further to get:\n   \\[ y = 2x \\]\n\nThe equation of the line is \\( y = 2x \\).\n\nThis is the equation we need to graph. \n\n**Step-by-step verification:**\n- The slope of the line is 2. This means for every 1 unit increase in \\( x \\), \\( y \\) increases by 2 units.\n- The line must pass through (1, 2). Let's check:\n  - If we substitute \\( x = 1 \\) into the equation \\( y = 2x \\):\n    \\[ y = 2(1) = 2 \\]\n  - The line goes through the point (1, 2).\n\nTherefore, the graph of the line with slope 2 that passes through the point (1, 2) is correctly represented by the equation \\( y = 2x \\).\n\nAnswer: The graph of the line is represented by \\( y = 2x \\)."}], "id": "000000000068"}
```
The data do not contain image, so training would hang. Maybe you could transform the parquet file into json format for training with image.

**Comment by anindya-saha** [comment]
Hi @John-Ge I am actually using the `mixed_conversation.jsonl` which has the `image` tag. I am concerned do we need the `image` tag or the `images` tag ?

**Comment by John-Ge** [comment]
The `<image>` token would be replaced with image feature whose original image is in the `image` tag of the data item.

**Comment by anindya-saha** [comment]
Thanks @John-Ge My question was the correct token would be `image` or `images` with an `s`. Also I am using the `mixed_conversation.jsonl` and that has the `image` token, but still the job hangs.

**Comment by John-Ge** [comment]
The token should be `image`. There should be a key of `image` in the data which shows the path for the image:

```json
{
    "image": "image.jpg",
    "conversations": [{"from": "human", "value": "Which of the following shows the graph of the line with a slope of $2$ and goes through the point $(1, 2)$?\n\nPlease conclude your answer as Answer: xxx at the end if possible."}, {"from": "gpt", "value": "To find the graph of a line with a given slope and point, we can use the point-slope form of the equation of a line:\n\n\\[ y - y_1 = m(x - x_1) \\]\n\nWhere \\( m \\) is the slope and \\( (x_1, y_1) \\) is the given point on the line.\n\nGiven:\n- Slope (\\( m \\)) = 2\n- Point (\\( x_1, y_1 \\)) = (1, 2)\n\nPlug these values into the point-slope formula:\n\n\\[ y - 2 = 2(x - 1) \\]\n\nNow, simplify this equation to get it into slope-intercept form \\( y = mx + b \\):\n\n1. Distribute the slope (2) on the right side:\n   \\[ y - 2 = 2x - 2 \\]\n\n2. Add 2 to both sides to solve for \\( y \\):\n   \\[ y = 2x - 2 + 2 \\]\n\n3. Simplify further to get:\n   \\[ y = 2x \\]\n\nThe equation of the line is \\( y = 2x \\).\n\nThis is the equation we need to graph. \n\n**Step-by-step verification:**\n- The slope of the line is 2. This means for every 1 unit increase in \\( x \\), \\( y \\) increases by 2 units.\n- The line must pass through (1, 2). Let's check:\n  - If we substitute \\( x = 1 \\) into the equation \\( y = 2x \\):\n    \\[ y = 2(1) = 2 \\]\n  - The line goes through the point (1, 2).\n\nTherefore, the graph of the line with slope 2 that passes through the point (1, 2) is correctly represented by the equation \\( y = 2x \\).\n\nAnswer: The graph of the line is represented by \\( y = 2x \\)."}], "id": "000000000068"}
```

**Comment by yesokyin** [comment]
你好，请问这个问题解决了么，遇到了同样的问题

**Comment by anindya-saha** [comment]
@yesokyin No, it is not solved.

**Comment by xuanda-d** [comment]
mixed_conversation.jsonl里有些数据没有图像



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 16, 2025 12:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QwenLM/Qwen2.5-VL] Finetuning Qwen 2.5 VL 3B with Deepspeed ishanging and not progressing on a g5.12xlarge (4 A10 Gpus) (Issue #1173)


yesokyin left a comment (QwenLM/Qwen2.5-VL#1173)
 
你好，请问这个问题解决了么，遇到了同样的问题

**Comment by yesokyin** [comment]
> [@yesokyin](https://github.com/yesokyin) No, it is not solved.

You can check if the issue is related to wandb. When the code hangs, press the Enter key. If wandb options appear, select the corresponding one.

**Comment by anindya-saha** [comment]
@yesokyin I do not use wandb, I disabled that.
