### ISSUE TITLE
vllm搭载7b的awq版本显存使用不符合预期

### ISSUE THREAD

**Issue by wciq1208** [QwenLM/Qwen2.5-VL#55]
使用如下命令启动vllm（readme里描述的版本），并固定住block的数量为2048，每个block size大小为16
```bash
vllm serve /hestia/model/Qwen2-VL-7B-Instruct-AWQ --quantization awq --num-gpu-blocks-override 2048 --port 8002 --served-model-name qwenvl --swap-space 0
```
在启动后推理了，推理是1的并发不停的请求，一段时间内显存占用固定为差不多14G；
然而在1个多小时之后，vllm显存占用变成了18G，2个小时后占用变成了20G
![image](https://github.com/user-attachments/assets/0f7950df-3bcc-46a7-84d4-9b9d7ee75d98)
![image](https://github.com/user-attachments/assets/ef29709f-ae9a-407c-867b-37e2160045b1)

kv cache占用计算应该是32768 * 28 * 4 * 128 * 2 * 2 / (1024 ** 3) = 1.75G
CUDA graph的显存占用按照vllm的说法显存占用预计1-3G之间
下面是vllm刚启动时的日志
```bash
INFO 08-31 12:19:24 api_server.py:440] vLLM API server version 0.5.5
INFO 08-31 12:19:24 api_server.py:441] args: Namespace(model_tag='/hestia/model/Qwen2-VL-7B-Instruct-AWQ', host=None, port=8002, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, model='/hestia/model/Qwen2-VL-7B-Instruct-AWQ', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=0.0, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=2048, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization='awq', rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=['qwenvl'], qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, engine_use_ray=False, disable_log_requests=False, max_log_len=None, dispatch_function=<function serve at 0x7f5e56ce5e40>)
INFO 08-31 12:19:24 awq_marlin.py:93] Detected that the model can run with awq_marlin, however you specified quantization=awq explicitly, so forcing awq. Use quantization=awq_marlin for faster inference
WARNING 08-31 12:19:24 config.py:321] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 08-31 12:19:24 api_server.py:144] Multiprocessing frontend to use ipc:///tmp/4223f246-e8a4-499e-8dc0-a9765f58eee9 for RPC Path.
INFO 08-31 12:19:24 api_server.py:161] Started engine process with PID 8323
INFO 08-31 12:19:28 awq_marlin.py:93] Detected that the model can run with awq_marlin, however you specified quantization=awq explicitly, so forcing awq. Use quantization=awq_marlin for faster inference
WARNING 08-31 12:19:28 config.py:321] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 08-31 12:19:28 llm_engine.py:212] Initializing an LLM engine (v0.5.5) with config: model='/hestia/model/Qwen2-VL-7B-Instruct-AWQ', speculative_config=None, tokenizer='/hestia/model/Qwen2-VL-7B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=qwenvl, use_v2_block_manager=False, num_scheduler_steps=1, enable_prefix_caching=False, use_async_output_proc=True)
[rank0]:[W831 12:19:29.063966970 ProcessGroupGloo.cpp:712] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
INFO 08-31 12:19:29 model_runner.py:991] Starting to load model /hestia/model/Qwen2-VL-7B-Instruct-AWQ...
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:02<00:02,  2.37s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:04<00:00,  2.11s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:04<00:00,  2.15s/it]

INFO 08-31 12:19:34 model_runner.py:1002] Loading model weights took 6.6757 GB
INFO 08-31 12:19:45 llm_engine.py:455] Overriding num_gpu_blocks=7128 with num_gpu_blocks_override=2048
INFO 08-31 12:19:45 gpu_executor.py:122] # GPU blocks: 2048, # CPU blocks: 0
INFO 08-31 12:19:45 model_runner.py:1302] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 08-31 12:19:45 model_runner.py:1306] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 08-31 12:20:01 model_runner.py:1421] Graph capturing finished in 16 secs.
INFO 08-31 12:20:02 api_server.py:209] vLLM to use /tmp/tmp9rerseq3 as PROMETHEUS_MULTIPROC_DIR
WARNING 08-31 12:20:02 serving_embedding.py:190] embedding_mode is False. Embedding API will not work.
INFO 08-31 12:20:02 launcher.py:20] Available routes are:
INFO 08-31 12:20:02 launcher.py:28] Route: /openapi.json, Methods: HEAD, GET
INFO 08-31 12:20:02 launcher.py:28] Route: /docs, Methods: HEAD, GET
INFO 08-31 12:20:02 launcher.py:28] Route: /docs/oauth2-redirect, Methods: HEAD, GET
INFO 08-31 12:20:02 launcher.py:28] Route: /redoc, Methods: HEAD, GET
INFO 08-31 12:20:02 launcher.py:28] Route: /health, Methods: GET
INFO 08-31 12:20:02 launcher.py:28] Route: /tokenize, Methods: POST
INFO 08-31 12:20:02 launcher.py:28] Route: /detokenize, Methods: POST
INFO 08-31 12:20:02 launcher.py:28] Route: /v1/models, Methods: GET
INFO 08-31 12:20:02 launcher.py:28] Route: /version, Methods: GET
INFO 08-31 12:20:02 launcher.py:28] Route: /v1/chat/completions, Methods: POST
INFO 08-31 12:20:02 launcher.py:28] Route: /v1/completions, Methods: POST
INFO 08-31 12:20:02 launcher.py:28] Route: /v1/embeddings, Methods: POST
INFO 08-31 12:20:02 launcher.py:33] Launching Uvicorn with --limit_concurrency 32765. To avoid this limit at the expense of performance run with --disable-frontend-multiprocessing
INFO:     Started server process [8313]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)
```

下面是1个多小时后显存占用变为18G时的vllm metrics，可以看到num_gpu_blocks还是参数里指定的2048并没有额外增加
```
# HELP vllm:cache_config_info Information of the LLMEngine CacheConfig
# TYPE vllm:cache_config_info gauge
vllm:cache_config_info{block_size="16",cache_dtype="auto",cpu_offload_gb="0",enable_prefix_caching="False",gpu_memory_utilization="0.9",num_cpu_blocks="0",num_gpu_blocks="2048",num_gpu_blocks_override="2048",sliding_window="None",swap_space_bytes="0.0"} 1.0
# HELP vllm:num_requests_running Number of requests currently running on GPU.
# TYPE vllm:num_requests_running gauge
vllm:num_requests_running{model_name="qwenvl"} 0.0
# HELP vllm:num_requests_swapped Number of requests swapped to CPU.
# TYPE vllm:num_requests_swapped gauge
vllm:num_requests_swapped{model_name="qwenvl"} 0.0
# HELP vllm:num_requests_waiting Number of requests waiting to be processed.
# TYPE vllm:num_requests_waiting gauge
vllm:num_requests_waiting{model_name="qwenvl"} 0.0
# HELP vllm:gpu_cache_usage_perc GPU KV-cache usage. 1 means 100 percent usage.
# TYPE vllm:gpu_cache_usage_perc gauge
vllm:gpu_cache_usage_perc{model_name="qwenvl"} 0.0
# HELP vllm:cpu_cache_usage_perc CPU KV-cache usage. 1 means 100 percent usage.
# TYPE vllm:cpu_cache_usage_perc gauge
vllm:cpu_cache_usage_perc{model_name="qwenvl"} 0.0
# HELP vllm:cpu_prefix_cache_hit_rate CPU prefix cache block hit rate.
# TYPE vllm:cpu_prefix_cache_hit_rate gauge
vllm:cpu_prefix_cache_hit_rate{model_name="qwenvl"} -1.0
# HELP vllm:gpu_prefix_cache_hit_rate GPU prefix cache block hit rate.
# TYPE vllm:gpu_prefix_cache_hit_rate gauge
vllm:gpu_prefix_cache_hit_rate{model_name="qwenvl"} -1.0
# HELP vllm:avg_prompt_throughput_toks_per_s Average prefill throughput in tokens/s.
# TYPE vllm:avg_prompt_throughput_toks_per_s gauge
vllm:avg_prompt_throughput_toks_per_s{model_name="qwenvl"} 1000.8895560597971
# HELP vllm:avg_generation_throughput_toks_per_s Average generation throughput in tokens/s.
# TYPE vllm:avg_generation_throughput_toks_per_s gauge
vllm:avg_generation_throughput_toks_per_s{model_name="qwenvl"} 10.987809497662443
# HELP vllm:num_preemptions_total Cumulative number of preemption from the engine.
# TYPE vllm:num_preemptions_total counter
vllm:num_preemptions_total{model_name="qwenvl"} 2.0
# HELP vllm:prompt_tokens_total Number of prefill tokens processed.
# TYPE vllm:prompt_tokens_total counter
vllm:prompt_tokens_total{model_name="qwenvl"} 1.325233e+06
# HELP vllm:generation_tokens_total Number of generation tokens processed.
# TYPE vllm:generation_tokens_total counter
vllm:generation_tokens_total{model_name="qwenvl"} 152004.0
# HELP vllm:request_success_total Count of successfully processed requests.
# TYPE vllm:request_success_total counter
vllm:request_success_total{finished_reason="length",model_name="qwenvl"} 1.0
vllm:request_success_total{finished_reason="stop",model_name="qwenvl"} 258.0
# HELP vllm:time_to_first_token_seconds Histogram of time to first token in seconds.
# TYPE vllm:time_to_first_token_seconds histogram
vllm:time_to_first_token_seconds_sum{model_name="qwenvl"} 1160.4357147216797
vllm:time_to_first_token_seconds_bucket{le="0.001",model_name="qwenvl"} 0.0
vllm:time_to_first_token_seconds_bucket{le="0.005",model_name="qwenvl"} 0.0
vllm:time_to_first_token_seconds_bucket{le="0.01",model_name="qwenvl"} 0.0
vllm:time_to_first_token_seconds_bucket{le="0.02",model_name="qwenvl"} 0.0
vllm:time_to_first_token_seconds_bucket{le="0.04",model_name="qwenvl"} 0.0
vllm:time_to_first_token_seconds_bucket{le="0.06",model_name="qwenvl"} 0.0
vllm:time_to_first_token_seconds_bucket{le="0.08",model_name="qwenvl"} 0.0
vllm:time_to_first_token_seconds_bucket{le="0.1",model_name="qwenvl"} 0.0
vllm:time_to_first_token_seconds_bucket{le="0.25",model_name="qwenvl"} 0.0
vllm:time_to_first_token_seconds_bucket{le="0.5",model_name="qwenvl"} 0.0
vllm:time_to_first_token_seconds_bucket{le="0.75",model_name="qwenvl"} 0.0
vllm:time_to_first_token_seconds_bucket{le="1.0",model_name="qwenvl"} 0.0
vllm:time_to_first_token_seconds_bucket{le="2.5",model_name="qwenvl"} 2.0
vllm:time_to_first_token_seconds_bucket{le="5.0",model_name="qwenvl"} 258.0
vllm:time_to_first_token_seconds_bucket{le="7.5",model_name="qwenvl"} 259.0
vllm:time_to_first_token_seconds_bucket{le="10.0",model_name="qwenvl"} 259.0
vllm:time_to_first_token_seconds_bucket{le="+Inf",model_name="qwenvl"} 261.0
vllm:time_to_first_token_seconds_count{model_name="qwenvl"} 261.0
# HELP vllm:time_per_output_token_seconds Histogram of time per output token in seconds.
# TYPE vllm:time_per_output_token_seconds histogram
vllm:time_per_output_token_seconds_sum{model_name="qwenvl"} 2862.518277168274
vllm:time_per_output_token_seconds_bucket{le="0.01",model_name="qwenvl"} 4.0
vllm:time_per_output_token_seconds_bucket{le="0.025",model_name="qwenvl"} 88693.0
vllm:time_per_output_token_seconds_bucket{le="0.05",model_name="qwenvl"} 151736.0
vllm:time_per_output_token_seconds_bucket{le="0.075",model_name="qwenvl"} 151737.0
vllm:time_per_output_token_seconds_bucket{le="0.1",model_name="qwenvl"} 151740.0
vllm:time_per_output_token_seconds_bucket{le="0.15",model_name="qwenvl"} 151740.0
vllm:time_per_output_token_seconds_bucket{le="0.2",model_name="qwenvl"} 151742.0
vllm:time_per_output_token_seconds_bucket{le="0.3",model_name="qwenvl"} 151743.0
vllm:time_per_output_token_seconds_bucket{le="0.4",model_name="qwenvl"} 151743.0
vllm:time_per_output_token_seconds_bucket{le="0.5",model_name="qwenvl"} 151743.0
vllm:time_per_output_token_seconds_bucket{le="0.75",model_name="qwenvl"} 151743.0
vllm:time_per_output_token_seconds_bucket{le="1.0",model_name="qwenvl"} 151743.0
vllm:time_per_output_token_seconds_bucket{le="2.5",model_name="qwenvl"} 151743.0
vllm:time_per_output_token_seconds_bucket{le="+Inf",model_name="qwenvl"} 151743.0
vllm:time_per_output_token_seconds_count{model_name="qwenvl"} 151743.0
# HELP vllm:e2e_request_latency_seconds Histogram of end to end request latency in seconds.
# TYPE vllm:e2e_request_latency_seconds histogram
vllm:e2e_request_latency_seconds_sum{model_name="qwenvl"} 2507.4191823005676
vllm:e2e_request_latency_seconds_bucket{le="1.0",model_name="qwenvl"} 0.0
vllm:e2e_request_latency_seconds_bucket{le="2.5",model_name="qwenvl"} 0.0
vllm:e2e_request_latency_seconds_bucket{le="5.0",model_name="qwenvl"} 49.0
vllm:e2e_request_latency_seconds_bucket{le="10.0",model_name="qwenvl"} 206.0
vllm:e2e_request_latency_seconds_bucket{le="15.0",model_name="qwenvl"} 239.0
vllm:e2e_request_latency_seconds_bucket{le="20.0",model_name="qwenvl"} 249.0
vllm:e2e_request_latency_seconds_bucket{le="30.0",model_name="qwenvl"} 255.0
vllm:e2e_request_latency_seconds_bucket{le="40.0",model_name="qwenvl"} 256.0
vllm:e2e_request_latency_seconds_bucket{le="50.0",model_name="qwenvl"} 257.0
vllm:e2e_request_latency_seconds_bucket{le="60.0",model_name="qwenvl"} 257.0
vllm:e2e_request_latency_seconds_bucket{le="+Inf",model_name="qwenvl"} 259.0
vllm:e2e_request_latency_seconds_count{model_name="qwenvl"} 259.0
# HELP vllm:request_prompt_tokens Number of prefill tokens processed.
# TYPE vllm:request_prompt_tokens histogram
vllm:request_prompt_tokens_sum{model_name="qwenvl"} 1.315135e+06
vllm:request_prompt_tokens_bucket{le="1.0",model_name="qwenvl"} 0.0
vllm:request_prompt_tokens_bucket{le="2.0",model_name="qwenvl"} 0.0
vllm:request_prompt_tokens_bucket{le="5.0",model_name="qwenvl"} 0.0
vllm:request_prompt_tokens_bucket{le="10.0",model_name="qwenvl"} 0.0
vllm:request_prompt_tokens_bucket{le="20.0",model_name="qwenvl"} 0.0
vllm:request_prompt_tokens_bucket{le="50.0",model_name="qwenvl"} 0.0
vllm:request_prompt_tokens_bucket{le="100.0",model_name="qwenvl"} 0.0
vllm:request_prompt_tokens_bucket{le="200.0",model_name="qwenvl"} 0.0
vllm:request_prompt_tokens_bucket{le="500.0",model_name="qwenvl"} 0.0
vllm:request_prompt_tokens_bucket{le="1000.0",model_name="qwenvl"} 0.0
vllm:request_prompt_tokens_bucket{le="2000.0",model_name="qwenvl"} 0.0
vllm:request_prompt_tokens_bucket{le="5000.0",model_name="qwenvl"} 17.0
vllm:request_prompt_tokens_bucket{le="10000.0",model_name="qwenvl"} 257.0
vllm:request_prompt_tokens_bucket{le="20000.0",model_name="qwenvl"} 259.0
vllm:request_prompt_tokens_bucket{le="+Inf",model_name="qwenvl"} 259.0
vllm:request_prompt_tokens_count{model_name="qwenvl"} 259.0
# HELP vllm:request_generation_tokens Number of generation tokens processed.
# TYPE vllm:request_generation_tokens histogram
vllm:request_generation_tokens_sum{model_name="qwenvl"} 96594.0
vllm:request_generation_tokens_bucket{le="1.0",model_name="qwenvl"} 0.0
vllm:request_generation_tokens_bucket{le="2.0",model_name="qwenvl"} 0.0
vllm:request_generation_tokens_bucket{le="5.0",model_name="qwenvl"} 2.0
vllm:request_generation_tokens_bucket{le="10.0",model_name="qwenvl"} 12.0
vllm:request_generation_tokens_bucket{le="20.0",model_name="qwenvl"} 22.0
vllm:request_generation_tokens_bucket{le="50.0",model_name="qwenvl"} 42.0
vllm:request_generation_tokens_bucket{le="100.0",model_name="qwenvl"} 82.0
vllm:request_generation_tokens_bucket{le="200.0",model_name="qwenvl"} 144.0
vllm:request_generation_tokens_bucket{le="500.0",model_name="qwenvl"} 210.0
vllm:request_generation_tokens_bucket{le="1000.0",model_name="qwenvl"} 247.0
vllm:request_generation_tokens_bucket{le="2000.0",model_name="qwenvl"} 255.0
vllm:request_generation_tokens_bucket{le="5000.0",model_name="qwenvl"} 257.0
vllm:request_generation_tokens_bucket{le="10000.0",model_name="qwenvl"} 258.0
vllm:request_generation_tokens_bucket{le="20000.0",model_name="qwenvl"} 259.0
vllm:request_generation_tokens_bucket{le="+Inf",model_name="qwenvl"} 259.0
vllm:request_generation_tokens_count{model_name="qwenvl"} 259.0
# HELP vllm:request_params_n Histogram of the n request parameter.
# TYPE vllm:request_params_n histogram
vllm:request_params_n_sum{model_name="qwenvl"} 259.0
vllm:request_params_n_bucket{le="1.0",model_name="qwenvl"} 259.0
vllm:request_params_n_bucket{le="2.0",model_name="qwenvl"} 259.0
vllm:request_params_n_bucket{le="5.0",model_name="qwenvl"} 259.0
vllm:request_params_n_bucket{le="10.0",model_name="qwenvl"} 259.0
vllm:request_params_n_bucket{le="20.0",model_name="qwenvl"} 259.0
vllm:request_params_n_bucket{le="+Inf",model_name="qwenvl"} 259.0
vllm:request_params_n_count{model_name="qwenvl"} 259.0
# HELP vllm:request_params_best_of Histogram of the best_of request parameter.
# TYPE vllm:request_params_best_of histogram
vllm:request_params_best_of_sum{model_name="qwenvl"} 259.0
vllm:request_params_best_of_bucket{le="1.0",model_name="qwenvl"} 259.0
vllm:request_params_best_of_bucket{le="2.0",model_name="qwenvl"} 259.0
vllm:request_params_best_of_bucket{le="5.0",model_name="qwenvl"} 259.0
vllm:request_params_best_of_bucket{le="10.0",model_name="qwenvl"} 259.0
vllm:request_params_best_of_bucket{le="20.0",model_name="qwenvl"} 259.0
vllm:request_params_best_of_bucket{le="+Inf",model_name="qwenvl"} 259.0
vllm:request_params_best_of_count{model_name="qwenvl"} 259.0
```

现在有两个问题：

1. 为什么实际占用比预期的要大，14G > (6.6757 + 3 + 1.75=11.4257G)，不过也有可能中间变量就是能产生这个gap
2. 为什么运行长时间后在block数量没变化的情况下显存占用会增长到18G和20G，是否由碎片或者CUDA自己的缓存引起，如果是的话vllm的模型代码里可不可以在推理结束后执行类似torch.cuda.empty_cache()的方法进行释放，我之前用huggingface用别的模型时也观察到同样的现象，虽然不知道是不是同样的原因，但那次用torch.cuda.empty_cache()解决了

**Comment by Mr-Loevan** [comment]
是的我也遇到了，推理过程中的显存会暴增。

**Comment by wciq1208** [comment]
> 是的我也遇到了，推理过程中的显存会暴增。

我尝试临时解决了一下，把那个fork出来的vllm仓库当中vllm/model_executor/models/qwen2_vl.py文件里Qwen2VLForConditionalGeneration类的compute_logits函数从
```python
    def compute_logits(self, hidden_states: torch.Tensor,
                       sampling_metadata: SamplingMetadata) -> torch.Tensor:
        logits = self.logits_processor(self.lm_head, hidden_states,
                                       sampling_metadata)
        return logits
```
改为
```python
    def compute_logits(self, hidden_states: torch.Tensor,
                       sampling_metadata: SamplingMetadata) -> torch.Tensor:
        logits = self.logits_processor(self.lm_head, hidden_states,
                                       sampling_metadata)
        torch.cuda.empty_cache()
        return logits
```
观察到的结果如下：

1. 加载后的显存为11.5G，符合6.6757 + 3 + 1.75=11.4257G的结论
2. 推理时上涨到13.6G,那么这2.1G的gap就是推理时的额外overhead
3. CUDA graph推理性能从85 tokens/s下降到80 tokens/s，enforce模式推理性能从35 tokens/s下降到33 tokens/s
4. 目前跑了1.5小时了内存稳定保持第一点所说的规律


当然，想要性能影响尽量的小，应该把torch.cuda.empty_cache()放到整个推理结束之后进行，而且不知道这个函数会不会对cuda stream的并发安全造成风险
@fyabc 大佬帮看一下怎么改合适

**Comment by fyabc** [comment]
> > 是的我也遇到了，推理过程中的显存会暴增。
> 
> 我尝试临时解决了一下，把那个fork出来的vllm仓库当中vllm/model_executor/models/qwen2_vl.py文件里Qwen2VLForConditionalGeneration类的compute_logits函数从
> 
> ```python
>     def compute_logits(self, hidden_states: torch.Tensor,
>                        sampling_metadata: SamplingMetadata) -> torch.Tensor:
>         logits = self.logits_processor(self.lm_head, hidden_states,
>                                        sampling_metadata)
>         return logits
> ```
> 
> 改为
> 
> ```python
>     def compute_logits(self, hidden_states: torch.Tensor,
>                        sampling_metadata: SamplingMetadata) -> torch.Tensor:
>         logits = self.logits_processor(self.lm_head, hidden_states,
>                                        sampling_metadata)
>         torch.cuda.empty_cache()
>         return logits
> ```
> 
> 观察到的结果如下：
> 
> 1. 加载后的显存为11.5G，符合6.6757 + 3 + 1.75=11.4257G的结论
> 2. 推理时上涨到13.6G,那么这2.1G的gap就是推理时的额外overhead
> 3. CUDA graph推理性能从85 tokens/s下降到80 tokens/s，enforce模式推理性能从35 tokens/s下降到33 tokens/s
> 4. 目前跑了6小时了显存稳定保持第一点和第二点所说的规律
> 
> 当然，实际上这么改时不合适的，只能临时救急一下，想要性能影响尽量的小，应该把torch.cuda.empty_cache()放到整个推理结束之后进行，而且不知道这个函数会不会对cuda stream的并发安全造成风险 @fyabc 大佬帮看一下怎么改合适
> 
> 我搜了一下vllm那边的相关issue，这似乎不是一个新的问题，而是qwen1.5就有的问题，虽然不知道为什么没得到重视，但感觉还是要修一下，不然一张卡里如果还放些别的东西时，运行时间长了必然OOM [https://github.com/vllm-project/vllm/issues/5726](url)

您好，非常感谢您的反馈！我们会尽快查出显存泄漏的原因并修复。

**Comment by fyabc** [comment]
@wciq1208 您好，可以麻烦提供一下具体测试的GPU型号和显存吗？我们在本地暂时无法复现这个bug（7B-AWQ的显存占用保持在12GB，且没有观察到显著增长）

**Comment by wciq1208** [comment]
> @wciq1208 您好，可以麻烦提供一下具体测试的GPU型号和显存吗？我们在本地暂时无法复现这个bug（7B-AWQ的显存占用保持在12GB，且没有观察到显著增长）

RTX3090 24G两张，然后CUDA_VISIBLE_DEVICES=1屏蔽掉第一张

**Comment by wciq1208** [comment]
> > > 是的我也遇到了，推理过程中的显存会暴增。
> > 
> > 
> > 我试着写了一个插件，这样就能在不修改vllm源码的情况下临时解决
> > # 使用方法
> > ### 目录结构
> > ```shell
> > |-- plugins
> > |   |-- setup.py
> > |   |-- vllm_clean_cuda_cache
> > |   |   |-- __init__.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### setup.py
> > ```python
> > from setuptools import setup
> > 
> > setup(name='vllm_clean_cuda_cache',
> >       version='0.1',
> >       packages=['vllm_clean_cuda_cache'],
> >       entry_points={
> >           'vllm.general_plugins':
> >           ["clean_cuda_cache = vllm_clean_cuda_cache:register"]
> >       })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### **init**.py
> > ```python
> > # coding = utf-8
> > 
> > from typing import Optional, List
> > 
> > import torch
> > from vllm.worker.worker_base import LocalOrDistributedWorkerBase
> > from vllm.sequence import ExecuteModelRequest
> > from vllm.model_executor.layers.sampler import SamplerOutput
> > 
> > 
> > # export VLLM_PLUGINS=clean_cuda_cache
> > 
> > def execute_model(self, execute_model_req: Optional[ExecuteModelRequest] = None, ) -> Optional[List[SamplerOutput]]:
> >     res = self.origin_execute_model(execute_model_req, )
> >     torch.cuda.empty_cache()
> >     return res
> > 
> > 
> > def register():
> >     if torch.cuda.is_available() and not getattr(LocalOrDistributedWorkerBase, "origin_execute_model", None):
> >         LocalOrDistributedWorkerBase.origin_execute_model = LocalOrDistributedWorkerBase.execute_model
> >         LocalOrDistributedWorkerBase.execute_model = execute_model
> >         print(LocalOrDistributedWorkerBase.origin_execute_model)
> >         print(LocalOrDistributedWorkerBase.execute_model)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 安装
> > ```shell
> > pip -e plugins
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 运行vllm前运行
> > ```shell
> > export VLLM_PLUGINS=clean_cuda_cache
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这时候再运行vllm，之后显存就正常了
> 
> @wciq1208 按照这个方法会出现报错，不加这个插件就没有报错，请问这个怎么解决呀
> 
> ```
> INFO 11-07 15:23:40 __init__.py:24] Found general plugin: clean_cuda_cache
> (VllmWorkerProcess pid=9808) INFO 11-07 15:23:40 __init__.py:24] Found general plugin: clean_cuda_cache
> INFO 11-07 15:23:40 __init__.py:29] Loaded general plugin: clean_cuda_cache
> (VllmWorkerProcess pid=9808) INFO 11-07 15:23:40 __init__.py:29] Loaded general plugin: clean_cuda_cache
> (VllmWorkerProcess pid=9808) INFO 11-07 15:23:40 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
> (VllmWorkerProcess pid=9808) ERROR 11-07 15:23:41 multiproc_worker_utils.py:229] Exception in worker VllmWorkerProcess while processing method init_device.
> (VllmWorkerProcess pid=9808) ERROR 11-07 15:23:41 multiproc_worker_utils.py:229] Traceback (most recent call last):
> (VllmWorkerProcess pid=9808) ERROR 11-07 15:23:41 multiproc_worker_utils.py:229]   File "/opt/conda/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 223, in _run_worker_process
> (VllmWorkerProcess pid=9808) ERROR 11-07 15:23:41 multiproc_worker_utils.py:229]     output = executor(*args, **kwargs)
> (VllmWorkerProcess pid=9808) ERROR 11-07 15:23:41 multiproc_worker_utils.py:229]   File "/opt/conda/lib/python3.10/site-packages/vllm/worker/worker.py", line 166, in init_device
> (VllmWorkerProcess pid=9808) ERROR 11-07 15:23:41 multiproc_worker_utils.py:229]     torch.cuda.set_device(self.device)
> (VllmWorkerProcess pid=9808) ERROR 11-07 15:23:41 multiproc_worker_utils.py:229]   File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 420, in set_device
> (VllmWorkerProcess pid=9808) ERROR 11-07 15:23:41 multiproc_worker_utils.py:229]     torch._C._cuda_setDevice(device)
> (VllmWorkerProcess pid=9808) ERROR 11-07 15:23:41 multiproc_worker_utils.py:229]   File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 300, in _lazy_init
> (VllmWorkerProcess pid=9808) ERROR 11-07 15:23:41 multiproc_worker_utils.py:229]     raise RuntimeError(
> (VllmWorkerProcess pid=9808) ERROR 11-07 15:23:41 multiproc_worker_utils.py:229] RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
> ```

用高点版本的vllm试试？我在0.5.5和0.6.1没问题。然后插件代码我现在也改了，改后会对性能及户没影响了
```python
# coding = utf-8

import gc
import threading
import time

import torch


# export VLLM_PLUGINS=clean_cuda_cache

class CleanTimepoint:
    interval_s = 600
    _t = None
    cuda_streem = torch.cuda.Stream()

    @classmethod
    def start(cls):
        if cls._t:
            return
        cls._t = threading.Thread(target=CleanTimepoint.run)
        cls._t.daemon = True
        cls._t.start()

    @classmethod
    def run(cls):
        while True:
            try:
                with torch.cuda.stream(cls.cuda_streem):
                    torch.cuda.empty_cache()
                gc.collect()
            except:
                ...
            time.sleep(cls.interval_s)


def register():
    CleanTimepoint.start()

```

**Comment by babyta** [comment]
> 是的我也遇到了，推理过程中的显存会暴增。

我的启动空载7g，推理17g。视频推理任务，可能是图片数量多有关。这个awq，gptq都不太好用呀

**Comment by wangyeqiang** [comment]
> 是的我也遇到了，推理过程中的显存会暴增。

我也是遇到同样问题，显存暴增，而且不降，必须重启才能解决。vllm版本是0.7.2 0.8.2都试过 不行。

**Comment by whitbrunn** [comment]
`--swap-space 0`  这个参数是你自己加的吗老哥 @wciq1208 

```
vllm: error: unrecognized arguments: ----swap-space 0
```

**Comment by wciq1208** [comment]
> `--swap-space 0` 这个参数是你自己加的吗老哥 [@wciq1208](https://github.com/wciq1208)
> 
> ```
> vllm: error: unrecognized arguments: ----swap-space 0
> ```

是的，可能后续版本的vllm没这个参数了
