### ISSUE TITLE
Qwen2.5-VL Fine-tuning Fails with CUDA error: too many resources requested for launch

### ISSUE THREAD

**Issue by HovChen** [QwenLM/Qwen2.5-VL#680]
I am trying to fine-tune Qwen2.5-VL-7B-Instruct using LoRA, but I keep encountering a CUDA error: too many resources requested for launch.
Even after reducing batch size and lowering image resolution, the issue persists.

My device is as follows:
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla V100S-PCIE-32GB          On  |   00000000:00:08.0 Off |                  Off |
| N/A   29C    P0             25W /  250W |       1MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla V100S-PCIE-32GB          On  |   00000000:00:09.0 Off |                  Off |
| N/A   28C    P0             24W /  250W |       1MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by ShuaiBai623** [comment]
Has flash attention implementation been enabled? It would save a lot of GPU memory.

**Comment by HovChen** [comment]
> Has flash attention implementation been enabled? It would save a lot of GPU memory.

Thank you for your advice, but I've solved the problem. I migrated the code to the NVIDIA A100 and it worked fine (I heard there was a precompile problem with the V100).

**Comment by ShashankKrishnaV** [comment]
Do you have any script to enable LoRA in QwenVL2.5?

**Comment by ShashankKrishnaV** [comment]
I am looking for a way to train only LLM part of the model. Can you guide me through the process on how that can be achieved.
