### ISSUE TITLE
使用vLLM运行Qwen2.5-VL-7B，3张24GB的显卡，运行报OOM

### ISSUE THREAD

**Issue by yao-di** [QwenLM/Qwen2.5-VL#923]
脚本代码如下：
```
from fastapi import FastAPI
from vllm import LLM, SamplingParams

# 设置可见的 GPU
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"

# 初始化模型
model = LLM(
            model="/data/ai-models/modelscope/Qwen2.5-VL-7B",
            tensor_parallel_size=2,
            gpu_memory_utilization=0.7
        )

# 初始化 FastAPI
app = FastAPI()

# 定义 API 端点
@app.post("/generate")
async def generate(prompt: str, max_tokens: int = 4096, temperature: float = 0.8):
    sampling_params = SamplingParams(temperature=temperature, max_tokens=max_tokens)
    outputs = model.generate([prompt], sampling_params)
    return {"response": outputs[0].outputs[0].text}

# 启动服务
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
```

报错如下：

> (VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242] Traceback (most recent call last):
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/executor/multiproc_worker_utils.py", line 236, in _run_worker_process
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     output = run_method(worker, method, args, kwargs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/utils.py", line 2196, in run_method
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/worker/worker.py", line 229, in determine_num_available_blocks
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     self.model_runner.profile_run()
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1235, in profile_run
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     self._dummy_run(max_num_batched_tokens, max_num_seqs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1346, in _dummy_run
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     self.execute_model(model_input, kv_caches, intermediate_tensors)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1724, in execute_model
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     hidden_or_intermediate_states = model_executable(
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]                                     ^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 1062, in forward
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     inputs_embeds = self.get_input_embeddings_v0(
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 1003, in get_input_embeddings_v0
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     video_embeds = self._process_video_input(video_input)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 925, in _process_video_input
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     video_embeds = self.visual(pixel_values_videos, grid_thw=grid_thw)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 641, in forward
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     hidden_states = blk(hidden_states,
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]                     ^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 369, in forward
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     x = x + self.attn(self.norm1(x),
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]             ^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 268, in forward
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     q, k, v = self.split_qkv(x)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]               ^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 239, in split_qkv
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     qkv = tensor_model_parallel_all_gather(qkv)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/distributed/communication_op.py", line 19, in tensor_model_parallel_all_gather
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return get_tp_group().all_gather(input_, dim)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/distributed/parallel_state.py", line 323, in all_gather
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     return self.device_communicator.all_gather(input_, dim)
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/distributed/device_communicators/base_device_communicator.py", line 58, in all_gather
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]     output_tensor = output_tensor.reshape(input_size[:dim] +
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=3897223) ERROR 03-10 09:59:57 multiproc_worker_utils.py:242] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.81 GiB. GPU 1 has a total capacity of 23.68 GiB of which 589.88 MiB is free. Including non-PyTorch memory, this process has 23.10 GiB memory in use. Of the allocated memory 19.88 GiB is allocated by PyTorch, and 2.80 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

_args
[rank0]:     engine = cls(
[rank0]:              ^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 276, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 421, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 102, in determine_num_available_blocks
[rank0]:     results = self.collective_rpc("determine_num_available_blocks")
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 316, in collective_rpc
[rank0]:     return self._run_workers(method, *args, **(kwargs or {}))
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/executor/mp_distributed_executor.py", line 185, in _run_workers
[rank0]:     driver_worker_output = run_method(self.driver_worker, sent_method,
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/utils.py", line 2196, in run_method
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/worker/worker.py", line 229, in determine_num_available_blocks
[rank0]:     self.model_runner.profile_run()
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1235, in profile_run
[rank0]:     self._dummy_run(max_num_batched_tokens, max_num_seqs)
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1346, in _dummy_run
[rank0]:     self.execute_model(model_input, kv_caches, intermediate_tensors)
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1724, in execute_model
[rank0]:     hidden_or_intermediate_states = model_executable(
[rank0]:                                     ^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 925, in _process_video_input
[rank0]:     video_embeds = self.visual(pixel_values_videos, grid_thw=grid_thw)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 641, in forward
[rank0]:     hidden_states = blk(hidden_states,
[rank0]:                     ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 369, in forward
[rank0]:     x = x + self.attn(self.norm1(x),
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 268, in forward
[rank0]:     q, k, v = self.split_qkv(x)
[rank0]:               ^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 239, in split_qkv
[rank0]:     qkv = tensor_model_parallel_all_gather(qkv)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/distributed/communication_op.py", line 19, in tensor_model_parallel_all_gather
[rank0]:     return get_tp_group().all_gather(input_, dim)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/distributed/parallel_state.py", line 323, in all_gather
[rank0]:     return self.device_communicator.all_gather(input_, dim)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ai/anaconda3/envs/vllm/lib/python3.12/site-packages/vllm/distributed/device_communicators/base_device_communicator.py", line 58, in all_gather
[rank0]:     output_tensor = output_tensor.reshape(input_size[:dim] +
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.81 GiB. GPU 0 has a total capacity of 23.68 GiB of which 594.69 MiB is free. Including non-PyTorch memory, this process has 23.10 GiB memory in use. Of the allocated memory 19.88 GiB is allocated by PyTorch, and 2.80 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by EthAnHoangg** [comment]
The same problem!

**Comment by yao-di** [comment]
After adding these two environment variables：“VLLM_USE_V1=1“、“VLLM_WORKER_MULTIPROC_METHOD=spawn“
it's OK

**Comment by EthAnHoangg** [comment]
Thank you, I solved my problem with your solution too. How did you get that?
